# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "34217a05a589a81a31677dc5ebe26c0b"
name = "Garantia extendida"
handle = "garantia-extendida"
application_url = "https://flashing-signing-rewards-fully.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders"

[auth]
redirect_urls = [
  "https://flashing-signing-rewards-fully.trycloudflare.com/auth/callback",
  "https://flashing-signing-rewards-fully.trycloudflare.com/auth/shopify/callback",
  "https://flashing-signing-rewards-fully.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
